### PR TITLE
Add parcel, scss, and typescript.

### PR DESCRIPTION
**Pull request by samwightt**
This pull request adds parcel, a zero-config alternative to webpack, which brings SCSS and Typescript support. I refactored a lot of the code and improved it a bit so that we're not relying on external CDNs for Bootstrap, jQuery and friends. This also compiles Bootstrap's sass on the fly, which means we can change its sass variables instead of overwriting class names. Last, we can also use Sass modules to split up our CSS code, as well as a ton of other Sass-specific features. Also Typescript with jquery 🤷‍♂

### CODE REVIEW

**Comment by samwightt** [comment]
Looks like it messed up the CSS, will update this and figure out what's going on.

**Comment by samwightt** [comment]
Finally fixed. Should be ready to review/merge. Lemme know what you think @ConnorBAdams

**Comment by samwightt** [comment]
Basic idea behind this is that we can now just edit the Bootstrap theme directly, changing line heights there instead of having to overwrite classes. This reduces the amount of CSS we deliver to the client and keeps code a lot more consistent. [See more about this here.](https://getbootstrap.com/docs/4.0/getting-started/theming/). Also gives us the ability to selectively import CSS. If we're not using a specific Boostrap component, we don't have to use it. Pretty simple. 🤷‍♂

**Comment by ConnorBAdams** [comment]
Sounds like a lot of unnecessary bloat for a static website. Compilation/load times are already going to be minimal since it isn't doing anything fancy.

**Pull request closed without merging**
